.TH PUDCONVERT 6 "Aug 2011" "Wargus v2.3"
.SH NAME
pudconvert \- Tool to convert Warcraft II map pud files to Stratagus map format
.SH SYNOPSIS
.B pudconvert
.I "inputfile [outputdir]"
.SH OPTIONS
.TP
.B inputfile
Input Warcraft II pud file
.TP
.B outputdir
Output directory where will be created map files
.SH "SEE ALSO"
.PD 0
.TP
\fIstratagus\fP(6), \fIwargus\fP(6), \fIwartool\fP(6)
.SH NOTES
Warcraft II is a registered trademark of Blizzard Entertainment.
.SH AUTHOR
Pudconvert is part of wartool, which is written by Lutz Sammer, Nehal Mistry, Jimmy Salmon, Pali Rohár and others.
.PP
This manual page was written by Pali Rohár <pali.rohar@gmail.com> .
