.TH WARGUS 6 "Aug 2011" "Wargus v2.3"
.SH NAME
wargus \- Warcraft II data game set for the Stratagus engine
.SH "DESCRIPTION"
Wargus is data game set for Stratagus engine. This is only launcher and wrapper for Stratagus. See \fIstratagus\fP(6) for all command line arguments.
.SH "SEE ALSO"
.PD 0
.TP
\fIstratagus\fP(6), \fIwartool\fP(6), \fIpudconvert\fP(6)
.SH NOTES
Warcraft II is a registered trademark of Blizzard Entertainment.
.SH AUTHOR
Wargus launcher is written by Pali Rohár <pali.rohar@gmail.com> .
.PP
This manual page was written by Pali Rohár <pali.rohar@gmail.com> .
