#!/bin/sh -e

# Source debconf library
. /usr/share/debconf/confmodule
db_capb backup

if [ "$(cat /usr/share/games/stratagus/wargus/extracted 2>/dev/null)" = "$(wartool -V)" ]; then
	db_set wargus/extractdata "false" || true
	db_stop || true
	exit 0
fi

db_get wargus/cdpath || true
TEMP=$RET
db_reset wargus/cdpath || true
db_set wargus/cdpath $TEMP || true

db_get wargus/extractmidi || true
TEMP=$RET
db_reset wargus/extractmidi || true
db_set wargus/extractmidi $TEMP || true

db_get wargus/extractvideo || true
TEMP=$RET
db_reset wargus/extractvideo || true
db_set wargus/extractvideo $TEMP || true

db_get wargus/ripcd || true
TEMP=$RET
db_reset wargus/ripcd || true
db_set wargus/ripcd $TEMP || true

db_reset wargus/extractdata || true

while true; do

	db_beginblock || true
	db_input critical wargus/extractdata || true
	db_endblock || true
	db_go || exit 10

	db_get wargus/extractdata || true
	EXTRACTDATA=$RET

	if [ "$EXTRACTDATA" = "false" ]; then
		break
	fi

	db_beginblock || true
	db_input critical wargus/cdpath || true
	db_input medium wargus/extractmidi || true
	db_input medium wargus/extractvideo || true
	db_input medium wargus/ripcd || true
	db_endblock || true
	db_go || exit 10

	db_get wargus/cdpath || true
	CDPATH=$RET

	db_get wargus/extractmidi || true
	EXTRACTMIDI=$RET

	db_get wargus/extractvideo || true
	EXTRACTVIDEO=$RET

	db_get wargus/ripcd || true
	RIPCD=$RET

	if [ -d "$CDPATH/data/" ]; then
		CDPATH="$CDPATH/data"
	elif [ -d "$CDPATH/DATA/" ]; then
		CDPATH="$CDPATH/DATA"
	fi

	db_set wargus/cdpath $CDPATH || true

	if [ -f "$CDPATH/rezdat.war" ] || [ -f "$CDPATH/REZDAT.WAR" ] || [ -f "$CDPATH/War Resources" ]; then
		break
	fi

	db_beginblock || true
	db_input critical wargus/nodata || true
	db_endblock || true
	db_go || exit 10

done

db_stop || true
