#!/bin/sh

set -e

# Source debconf library
. /usr/share/debconf/confmodule
db_version 2.0
db_capb backup

if [ "$1" != "configure" ] && [ "$1" != "reconfigure" ]; then
	exit 0;
fi

HAS_VERSION="$(cat /usr/share/games/stratagus/wargus/extracted 2>/dev/null)"
NEW_VERSION="$(wartool -V 2>/dev/null)"

if [ "$1" = "configure" ] && [ "$HAS_VERSION" = "$NEW_VERSION" ]; then
	db_set wargus/extractdata "false" || true
	db_stop || true
	exit 0
fi

db_reset wargus/extractdata || true
db_fset wargus/extractdata seen false || true
db_fset wargus/cdpath seen false || true
db_fset wargus/extractmidi seen false || true
db_fset wargus/extractvideo seen false || true
db_fset wargus/ripcd seen false || true

while true; do

	db_beginblock || true
	db_input critical wargus/extractdata || true
	db_endblock || true
	db_go || exit 10

	db_get wargus/extractdata || true
	if [ "$RET" = "false" ]; then
		break
	fi

	db_beginblock || true
	db_input critical wargus/cdpath || true
	db_input medium wargus/extractmidi || true
	db_input medium wargus/extractvideo || true
	db_input medium wargus/ripcd || true
	db_endblock || true
	db_go || continue

	db_get wargus/cdpath || true
	for CDPATH in "$RET" "$RET/data" "$RET/DATA"; do
		if [ -f "$CDPATH/rezdat.war" ] || [ -f "$CDPATH/REZDAT.WAR" ] || [ -f "$CDPATH/War Resources" ]; then
			db_set wargus/cdpath $CDPATH || true
			break
		fi
	done

	db_beginblock || true
	db_input critical wargus/nodata || true
	db_endblock || true
	db_go || continue

done

db_stop || true
