#!/bin/sh

set -e

. /usr/share/debconf/confmodule

extract() {
	db_get wargus/extractdata || true
	[ "X$RET" = "X" ] && { db_stop || true; return 0; }

	db_get wargus/cdpath || true
	CDPATH="$RET"

	db_get wargus/wartoolOptions || true 
	echo "$RET" | grep -q videos  && { ARGS="$ARGS -v"; }
	echo "$RET" | grep -q tracks  && { ARGS="$ARGS -r"; }
	echo "$RET" | grep -q exppack && { db_get wargus/expcdpath || true; CDPATHEXP="$RET"; }

	db_stop || true # don't understand this

	echo "wartool $ARGS $CDPATH /usr/share/games/stratagus/wargus" 
	wartool $ARGS "$CDPATH" /usr/share/games/stratagus/wargus || return $?
	if ! [ -z "$CDPATHEXP" ]; then
	    echo "Expansion Pack: wartool $ARGS $CDPATHEXP /usr/share/games/stratagus/wargus"
	    wartool $ARGS "$CDPATHEXP" /usr/share/games/stratagus/wargus || return $?
	fi
	[ -f /usr/share/sounds/sf2/TimGM6mb.sf2 ] && { cp /usr/share/sounds/sf2/TimGM6mb.sf2 /usr/share/games/stratagus/wargus/music; }

	db_stop || true # don't understand this
	return $?
}

if [ "$1" = "configure" ]; then
	extract || exit $?
fi

#DEBHELPER#

exit 0
