#!/bin/sh

set -e

. /usr/share/debconf/confmodule

extract() {

	db_get wargus/extractdata || true

	if [ "$RET" = "true" ]; then

		db_get wargus/cdpath || true

		CDPATH=${RET}
		EXTRACTVIDEO=
		EXTRACTMUSIC=

		if [ -d "${CDPATH}" ]; then

			db_get wargus/extractvideo || true
			if [ ${RET} = "true" ]; then
				EXTRACTVIDEO="-v"
			fi

			db_get wargus/extractmusic || true
			if [ ${RET} = "true" ]; then
				EXTRACTMUSIC="-m"
			fi

			db_stop || true
			echo "Extracting data from ${CDPATH} to /usr/share/games/stratagus/wargus"

			cd /usr/share/games/stratagus/wargus
			/usr/share/games/stratagus/wargus/build.sh -p ${CDPATH} -b /usr/bin -o /usr/share/games/stratagus/wargus -s -c ${EXTRACTVIDEO} ${EXTRACTMUSIC}
			return $?

		else

			db_stop || true
			echo "${RET} doesn't exist - can't extract Warcraft II data" >&2
			return 1

		fi

	fi

	db_stop || true
	return 0

}

if [ "$1" = "configure" ]; then
	extract || exit $?
fi

#DEBHELPER#

exit 0
